### ISSUE TITLE
Wynton Bench Slurm Job Failing

### ISSUE THREAD

**Issue by ellestad** [UCSF-HPC/wynton-bench#13]
Wynton-bench is working locally for me, but the Slurm job I had set up is no longer working after the code change/move to wynton-bench user.

Crontab entry:
```
SBATCH=/usr/bin/sbatch
BENCH_HOME=$HOME/wynton-bench

*/5 * * * * { cd $HOME/.crontab/$HOSTNAME/logs/; $SBATCH -t 30 -N 1 --job-name=wynton-bench --export=BENCH_HOME=$BENCH_HOME "$BENCH_HOME/cron-scripts/bench-files-tarball.sh"; } >> .crontab/${HOSTNAME}/logs/bench_files_tarball.log 2>&1
```
The output of the Slurm job is (for example):
```
==========================================
SLURM_JOB_ID = 290
SLURM_NODELIST = qb3-iogpu2
==========================================
mkdir: cannot create directory '/wynton-bench-logs': Permission denied
ERROR: Failed to create directory: /wynton-bench-logs/qb3-iogpu2
mkdir: cannot create directory '/wynton-bench-logs': Permission denied
ERROR: Failed to create directory: /wynton-bench-logs/qb3-iogpu2
mkdir: cannot create directory '/wynton-bench-logs': Permission denied
ERROR: Failed to create directory: /wynton-bench-logs/qb3-iogpu2
mkdir: cannot create directory '/wynton-bench-logs': Permission denied
ERROR: Failed to create directory: /wynton-bench-logs/qb3-iogpu2
```
Looks like it is trying to create the directory in the root of the file system instead of in the wynton-bench home directory.

I have edited out the hb's in ~wynton-bench/wynton-bench/bin/wynton-bench and replaced them with wynton-bench.

**Comment by HenrikBengtsson** [comment]
Commenting from phone: does it make difference if you use:

```
... --wrap "$BENCH_HOME/cron-scripts/bench-files-tarball.sh" ...
```

**Comment by HenrikBengtsson** [comment]
Actually, I think I know what's going on.  Please do a `git pull` and try again.  If my hypothesis is correct, then you'll get an informative error message.

**Comment by ellestad** [comment]
Well, that is a useful message.

```
ERROR: Environment variable not set: HOME
```
But, why did it work before when it was running as me?

The crontab was the same, without passing $HOME to Slurm.

**Comment by HenrikBengtsson** [comment]
So, yeah, crontab doesn't set HOME, so you need to manually set that in your `crontab -e` header.

> But, why did it work before when it was running as me?

Don't know and not sure what "before" is, but the script has had `$HOME` for 1.5 years, cf. https://github.com/ucsf-wynton/wynton-bench/blame/master/cron-scripts/bench-files-tarball.sh, so nothing changed there.

**Comment by HenrikBengtsson** [comment]
Since you mention Slurm, it's probably a combination of crontab not setting HOME and Slurm not calling your shell startup scripts.

**Comment by jlbl** [comment]
But crontab *does* set HOME.  Or, at least, it does in the quick test I ran on dev3.  I did `crontab -e`, entered this line
```
* * * * * env > /tmp/cronenv.txt
```
and got this result
```
[jlb@dev3 ~]$ cat /tmp/cronenv.txt 
XDG_SESSION_ID=1939
SHELL=/bin/sh
USER=jlb
PATH=/usr/bin:/bin
PWD=/wynton/home/sali/jlb
LANG=en_US.UTF-8
SHLVL=1
HOME=/wynton/home/sali/jlb
LOGNAME=jlb
XDG_RUNTIME_DIR=/run/user/11055
_=/usr/bin/env
```

**Comment by ellestad** [comment]
What I meant by "before" was, as of Wednesday the crontab below was working fine, submitting jobs to Slurm, running the jobs, etc. running from my account. But I don't want it to run as me, as I am an admin.

I had just copied and adapted your crontab which submits an SGE job on log1.

However, since the recent code updates and me moving it to the wynton-bench user, it is no longer working.

So I am not sure if I missed something in adapting the code to run as a different user from when I first did it or if there is something different in your code update that is not working with Slurm.

It does work fine from crontab on the local machine, just not when I try to submit it as a Slurm job.

But, anyway, not that big a deal, thanks for the help. I'll keep poking at it and see if I can get it to work.

```
SBATCH=/usr/bin/sbatch
BENCH_HOME=$HOME/wynton-bench

*/5 * * * * { cd $HOME/.crontab/$HOSTNAME/logs/; $SBATCH -t 30 -N 1 --job-name=wynton-bench --export=BENCH_HOME=$BENCH_HOME "$BENCH_HOME/cron-scripts/bench-files-tarball.sh"; } >> .crontab/${HOSTNAME}/logs/bench_files_tarball.log 2>&1
```

**Comment by HenrikBengtsson** [comment]
> But crontab does set HOME

My bad. Too little coffee, today or I'm mixing it up with another system.

Eitherway, none of my scripts unset HOME, so something else does.

**Comment by HenrikBengtsson** [comment]
> However, since the recent code updates and me moving it to the wynton-bench user, it is no longer working.

So, there are two things happening at once there.  Can you test running as you, to see if the problem only happens when running as root?

If it still happens when running as a regular user, you could try to narrow done the offending commit by trying different `git checkout <commit>` to find which an works and the first one that breaks it for you.

**Comment by HenrikBengtsson** [comment]
> ... ~~root~~ wynton-bench

**Comment by ellestad** [comment]
Hm, yes, it works as me with only "--export=BENCH_HOME=$BENCH_HOME", but with wynton-bench for some reason I need to add the following to the sbatch line:
```
--export=ALL,BENCH_HOME=$BENCH_HOME
```
One thing, if you include multiple --export statements, apparently it unsets everything except the last one.

So, for example if you include "--export=USER=$USER --export=HOME=$HOME" with your sbatch, $USER is unset and only $HOME is set. So if you want to set multiple variables, you need to use the comma delimiter, not set them separately.
