### ISSUE TITLE
How do I run wynton-bench?

### ISSUE THREAD

**Issue by ellestad** [UCSF-HPC/wynton-bench#9]
[eje@dev3 bin]$ ./wynton-bench
WARNING: Unknown drive '' - will try with TEST_DRIVE=''
ERROR: No such file: /wynton/home/cbi/hb/wynton-bench-logs/dev3/bench-files-tarb                                                     all__.log
[eje@dev3 bin]$ ./wynton-bench --help
Disk IO Benchmark Summary

Usage:
 wynton-bench [options]

Options:
 --help              Display this help
 --version           Display version
 --drive <drive>     The drive to report on
 --format <fmt>      Output format: spark (default), int, dbl
 --data-root <path>  Path to root data folder (default: ~hb/wynton-bench-logs)
 --hostname <host>   Host from where data was collected (default: dev3)
 --user <user>       User that collected data (default: hb)

Examples:
 wynton bench --drive /scratch
 wynton bench --drive /wynton/scratch
 wynton bench --drive /wynton/home
 wynton bench --drive /wynton/group

Requirements:
* spark: https://github.com/holman/spark

Version: 0.0.3
Copyright: Henrik Bengtsson (2020-2021)
License: GPL (>= 2.1) [https://www.gnu.org/licenses/gpl.html]
[eje@dev3 bin]$ ./wynton-bench --user eje --drive /wynton/home
ERROR: No such file: /wynton/home/cbi/hb/wynton-bench-logs/dev3/bench-files-tarball__wynton_home_cbi_eje.log
[eje@dev3 bin]$ mkdir ~/Documents/wynton-bench-logs
[eje@dev3 bin]$ ./wynton-bench --user eje --drive /wynton/home --data-root  ~/Documents/wynton-bench-logs
ERROR: No such folder: /wynton/home/admins/eje/Documents/wynton-bench-logs/dev3
[eje@dev3 bin]$ mkdir ~/Documents/wynton-bench-logs/dev3
[eje@dev3 bin]$ ./wynton-bench --user eje --drive /wynton/home --data-root  ~/Documents/wynton-bench-logs
ERROR: No such file: /wynton/home/admins/eje/Documents/wynton-bench-logs/dev3/bench-files-tarball__wynton_home_cbi_eje.log
[eje@dev3 bin]$ ./wynton-bench --user eje --drive /wynton/home --data-root  ~/Documents/wynton-bench-logs --hostname dev3
ERROR: No such file: /wynton/home/admins/eje/Documents/wynton-bench-logs/dev3/bench-files-tarball__wynton_home_cbi_eje.log

**Comment by HenrikBengtsson** [comment]
The `--user` option is to specify the user who has collected the data.  The only one this far is me (`--user hb`), which is the default.  To try without `--user`.    Note that `wynton-bench` is just a very(!) basic CLI tool for presenting the benchmarks already collected.

The script that runs a single benchmark is [bench-scripts/bench-files-tarball.sh](https://github.com/ucsf-wynton/wynton-bench/blob/master/bench-scripts/bench-files-tarball.sh).  I call [cron-scripts/bench-files-tarball.sh](https://github.com/ucsf-wynton/wynton-bench/blob/master/cron-scripts/bench-files-tarball.sh) via a cronjob to collect these on a regular basis.

**Comment by ellestad** [comment]
I'm trying to figure out from the scripts what needs to be done to run these benchmarks as a service account, rather than hb.

Have the setup steps been documented? A README or INSTALL would be super helpful.

**Comment by ellestad** [comment]
I've gotten as far as running the cron and outputting to ~eje/.crontab/$HOSTNAME/logs, but the job is erroring with a mktemp error.

BENCH_LOGFILE: '/wynton/home/admins/eje/wynton-bench-logs/qb3-hmid6/bench-files-tarball__wynton_home_admins_eje.log'
BENCH_LOGFILE (temporary): '/tmp/BENCH_LOGFILE.bbClvx'
mktemp: failed to create directory via template ‘/tmp/.wynton-bench/.bench.XXXXXX’: Permission denied

**Comment by jlbl** [comment]
Looks like `/tmp/.wynton-bench` *does* exist -- it's just owned by hb (at least on dev3). That's way Erik can't create a directory in there.

**Comment by HenrikBengtsson** [comment]
I've made a few updates + bug fixes so it works in a fresh setup.  The following should now work;

Setup:

```sh
$ git clone https://github.com/ucsf-wynton/wynton-bench.git
$ cd wynton-bench
$ make test-files
```

Running:

```sh
$ cd wynton-bench
$ export BENCH_HOME=$PWD
$ $BENCH_HOME/cron-scripts/bench-files-tarball.sh
```
which outputs:
```sh
BENCH_LOGFILE: '/wynton/home/bengtsson/hb-test/wynton-bench-logs/dev3/bench-files-tarball__tmp_hb-test.log'
BENCH_LOGFILE (temporary): '/tmp/hb-test/BENCH_LOGFILE.hTTRSZ'
BENCH_LOGFILE: '/wynton/home/bengtsson/hb-test/wynton-bench-logs/dev3/bench-files-tarball__wynton_home_bengtsson_hb-test.log'
BENCH_LOGFILE (temporary): '/tmp/hb-test/BENCH_LOGFILE.lpJ8F3'
```

with benchmark saved in:

```sh
$ ls -lrt ~/wynton-bench-logs/$HOSTNAME/
total 30
-rw-r--r--. 1 hb-test lsd  7091 Feb  2 15:52 bench-files-tarball__tmp_hb-test.log
-rw-r--r--. 1 hb-test lsd 22866 Feb  2 15:52 bench-files-tarball__wynton_home_bengtsson_hb-test.log
```

**Comment by HenrikBengtsson** [comment]
Those `bench-files-tarball_*.log` files hold the raw data in a tab-delimited format (which btw should really be re-named `*.tsv` at some point).

**Comment by ellestad** [comment]
Great, seems to be working now without error.

**Comment by HenrikBengtsson** [comment]
I've updated the [README](https://github.com/ucsf-wynton/wynton-bench/) with these confirmed low-level benchmarking instructions plus a little bit more info.
